steps:
  # Install dependencies
  - name: 'node:20'   
    entrypoint: 'npm'
    args: ['install']

  # Build the app
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Deploy through Cloud Run with Buildpacks (NO Dockerfile)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "qbot-india",
        "--source=.",
        "--region=asia-south1",
        "--platform=managed",
        "--allow-unauthenticated",
        "--timeout=300s",
        "--memory=1Gi",
        "--concurrency=80",
        "--min-instances=0",
      ]

timeout: '900s'